# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
source 'git@github.com:CocoaPods/Specs.git'
use_frameworks!

target 'IM' do
    pod 'XMPPFramework', '~> 3.6.6'
end

