# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

source 'git@github.com:CocoaPods/Specs.git'

target 'TrcBank' do
    pod 'ActionSheetPicker-3.0', '~> 2.0.2'
end

target 'TrcBankTests' do

end

target 'TrcBankUITests' do

end

